title: Theresa Medrano # your name (or website title) here
logo: "/images/IMG_3883.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Professional Data Analyst
  Cleveland, OH 
  <br><br>
  <a href="https://www.linkedin.com/in/tfmedrano/">View My LinkedIn Profile</a> 
  <br><br>
  I am a self-driven professional with a wide range of skills who communicates effectively and is comfortable collaborating in a team setting and with all levels of an organization. My strong analytical, project management, and organization skills have been key to my success and making an immediate impact anywhere I go. I bring a vast knowledge of Power BI report building, DAX coding, data analysis, and developing winning teams from the ground up. I am committed to success and look for roles that challenge me both personally and professionally.
<br><br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
